server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Swayam@73
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

#  security:
#    user:
#      name: admin
#      password: admin

# JWT Configuration
jwt:
  secret: your-super-secret-jwt-key-change-this-in-production
  expiration: 86400000

# Eureka Client - if you are using Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

## Actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
#  endpoint:
#    health:
#      show-details: always
#
#logging:
#  level:
#    org.springframework.security: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

